### ISSUE TITLE
Automatically determine if persist should be set to true for Actions

### ISSUE THREAD

**Issue by Geheiner** [smart-data-lake/smart-data-lake#112]
The output of most Actions in the Smart Datalake Builder have to be read again afterwards.
It would make sense if for those Actions, the results  automatically get persisted so that the underlying dataframes don't have to be recomputed everytime they are accessed.
In the current implementation, persist is set to false, which means that I have to set it to true in all my Actions that are not in the final output.

**Comment by zzeekk** [comment]
The implementation counts DataFrames reused in subsequent actions in init-phase, so that we can "persist/cache" them before the write operation in exec-phase.
It also tracks when postExec function when no Action needs the cached DataFrame anymore, and releases it automatically.
In my opinion the "persist" property of Actions to manually control caching isn't needed anymore, but it is left for the moment for backward compatibility as it is no problem if the same DataFrame is cached multiple times.
The feature can be disabled by setting java system property "sdl.enableAutomaticDataFrameCaching=false".
