### ISSUE TITLE
Generate Tables in relational databases automatically

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#217]
**Is your feature request related to a problem? Please describe.**
Related to #216 : SDL could create tables if they don't exist.

**Describe the solution you'd like**
SDL could generate tables on the fly if they don't exist yet (creating and executing CREATE TABLE scripts automatically). 

**Additional context**
Feasability needs to be checked. Also in regard of different jdbc driver, database systems and thefore different data types etc.
Maybe we need to limit the supported functionality to known types.

**Comment by zzeekk** [comment]
With JdbcDialects.get(jdbcUrl) one can get a JdbcDialect instance which can translate Spark <-> SQL data types.

**Comment by zzeekk** [comment]
Just found that we have a unit test that creates the database table from a DataFrame: 
https://github.com/smart-data-lake/smart-data-lake/blob/255b0efa3c284ab7f6ccfb1dc9b3ea2c7bc4829e/sdl-core/src/test/scala/io/smartdatalake/workflow/dataobject/JdbcTableDataObjectTest.scala#L54

You need to define option "createTableColumnTypes", because the datatype of DataFrames lacks precision for string and other datatypes...

Maybe we could define good defaults for this on the connection, and override it where necessary on the specific table?

**Comment by zzeekk** [comment]
JdbcTableDataObject can be created by specifying a createSql. Otherwise SDL tries to create the table in prepare phase by using JdbcTableConnection.createTableFromSchema, see #389.
