### ISSUE TITLE
Recovery not working for skipped and failed predecessors

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#356]
**Describe the bug**
Recovery doesn't work correctly if you have skipped and failed predecessor feeds.
Observed the following constellations with Feeds A - D

```
A   B
│   │
│   C
│   │
  D
```

A didn't have work, so is in state SKIPPED.
B FAILED, so C is CANCELLED. 
D is therefore also CANCELLED:

Feeds A and D are configured with 
`executionMode = { type = FailIfNoPartitionValuesMode }`

The recovery executes B + C + D.
Init fails, with error 
Root cause is 'IllegalStateException: (Action~D) Partition values are empty for mainInput int_error'

**To Reproduce**
Provide a minimum configuration file with feeds to reproduce the bug.

**Expected behavior**
In a normal run with the feeds above, feed D is also SKIPEED, because one of the predecessor feeds was skipped.
Recovery should do the same. 

**Additional context**
From a first look it seems that "SKIPPED" should have a higher priority than "CANCELLED". In this particular case, feed D should then be SKIPPED. 
A recovery would then still execute B + C (as it would in a normal run) but not execute feed D anymore.

**Comment by zzeekk** [comment]
Interesting. It's definitely a bug. It should not matter if Action D is executed in normal mode or recovery. The decision if it is skipped or no is done by the executionCondition. I assume in this case it is empty and the default is that the "Action is executed if no input subFeed is skipped.", see also https://github.com/smart-data-lake/smart-data-lake/blob/0a6dda684d387d5001cf0a688af20dd2aff368b2/sdl-core/src/main/scala/io/smartdatalake/workflow/action/Action.scala#L140

I guess that the subfeed with results from skipped Action A is not properly initialized as Skipped when in Recovery mode. I would start debugging at https://github.com/smart-data-lake/smart-data-lake/blob/0a6dda684d387d5001cf0a688af20dd2aff368b2/sdl-core/src/main/scala/io/smartdatalake/app/SmartDataLakeBuilder.scala#L218

**Comment by hiltpold** [comment]
Since Action A was skipped, the state file does not contain any results for this action. Therefore it cannot act as a potential initialSubFeed in the recovery run. 
But looking at 
https://github.com/smart-data-lake/smart-data-lake/blob/0a6dda684d387d5001cf0a688af20dd2aff368b2/sdl-core/src/main/scala/io/smartdatalake/workflow/action/Action.scala#L141
your guess is correct. One of the subfeeds (A or C) must have the field isSkipped=true in order that Action D is skipped. Indeed in normal mode the subfeed (the one originating from A) has the field isSkipped=true and while in recovery it has the field isSkipped=false. 

In the init phase
https://github.com/smart-data-lake/smart-data-lake/blob/0a6dda684d387d5001cf0a688af20dd2aff368b2/sdl-core/src/main/scala/io/smartdatalake/workflow/ActionDAGRun.scala#L111
the subfeeds get either initialized in line 118 if the current node is the InitDAGNode or they are returned already initialized by the run function. But somehow I truly miss the point where the subfeeds are initialized.

**Comment by zzeekk** [comment]
Created a unit test and fixed the bug. I added fake results for skipped actions in state file.
Can you test?

**Comment by pgruetter** [comment]
@zzeekk Saw the push, no problem. Tested and it works correctly now, thanks a lot for the fix!

In the test above, I made A fail on the first run. On the second run, only B, C + D were executed. 
The final state is then B=succeeded, C=succeeded, D=skipped

**Comment by pgruetter** [comment]
cherry-picked to develop in https://github.com/smart-data-lake/smart-data-lake/commit/5be17ff7a62c012ac6844fabb16eddfd788738d2
