### ISSUE TITLE
Support for Snowflake Snowpark

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#376]
**Is your feature request related to a problem? Please describe.**
With Snowpark Spark can be executed inside Snowflake (or a flavor of Spark?)

**Describe the solution you'd like**
Implement an Action to execute Snowpark Transformations.

**Additional context**
Documentation: https://docs.snowflake.com/en/developer-guide/snowpark/index.html
It seems that Snowflake copied or integrated large pieces of the Spark API. It must be analyzed if this could be used as Spark Version inside SDL or if it has to be handled as a separate Execution Engine. In that case there might be library problems to research...

**Comment by MarkusRothSBB** [comment]
This would be very interesting for SBB, as we are using Snowflake. HistorizeAction currently leads to a large amount of reads to the target Snowflake table, making processing non-trivial amounts of data very slow. If HistorizeAction would work directly inside Snowpark, I expect this to work orders of magnitude faster.

**Comment by MarkusRothSBB** [comment]
Update: According to Snowflake, Snowpark is now available von Azure. We could start experimenting on our infrastructure at SBB.

**Comment by MarkusRothSBB** [comment]
I looked into this a little bit: https://www.phdata.io/blog/spark-developers-guide-to-snowpark/

It seems that Snowpark is a completely separate library to spark, it just uses a similar API. I guess we could have a separate execution path for actions that have only Snowflake data objects as inputs and outputs that use Snowpark DataFrames rather than Spark DataFrames, but it seems like it would be a major undertaking.

It would be really nice to be able to ingest data from source systems with spark and then do the transformations within Snowflake using Snowpark within the same project, though.

**Comment by zzeekk** [comment]
I checked the ScalaDoc - as you said it "is a completely separate library to spark, it just uses a similar API".
https://docs.snowflake.com/en/developer-guide/snowpark/reference/scala/com/snowflake/snowpark/index.html
Source code is not available, i guess Snowflake doesn't need to open-source it as it's not a copy of Spark but just a similar API.
I think we could integrate it as another "execution engine", up to now we have "Spark DataFrames" and "File Input&OutputStream". Now we could add "Snowpark DataFrames".
It would be nice to reuse existing Actions (Copy/Deduplicate/HistorizeAction), but for that we would need to generalize the Spark and Snowpark API.
In a first step i propose to create a simple CopyAction for Snowpark, probably duplicating a lot of Code from SparkSubFeedAction.

**Comment by MarkusRothSBB** [comment]
I planned a week during December (13th to 19th) to hack around on this and see if I can get a prototype working.

**Comment by MarkusRothSBB** [comment]
I hacked around a bit and found a reasonably good way of abstracting DataFrame, Column and similar types into a DSL, which can then be implemented in Spark or Snowpark. It works like this:

A domain-specific language that defines DataFrame operations is defined as a [Language trait](https://github.com/smart-data-lake/smart-data-lake/blob/feature/376-dataframe-dsl/sdl-core/src/main/scala/io/smartdatalake/dataframe/DomainSpecificLanguage.scala). It also uses implicit classes to create methods on any objects extending the traits, so that regular Spark-like syntax can be used - e.g. calling the select method on an object implementing the DSL DataFrame trait.

The domain-specific language is implemented by [SparkLanguageImplementation](https://github.com/smart-data-lake/smart-data-lake/blob/feature/376-dataframe-dsl/sdl-core/src/main/scala/io/smartdatalake/dataframe/SparkLanguageImplementation.scala) and [SnowparkLanguageImplementation](https://github.com/smart-data-lake/smart-data-lake/blob/feature/376-dataframe-dsl/sdl-snowflake/src/main/scala/io/smartdatalake/dataframe/SnowparkLanguageImplementation.scala).

Business logic can then be implemented purely in the DSL. A caller, say a SparkSubFeed, may create an implicit SparkLanguageImplementation before calling into the DSL transformations - say into a HistorizeAction. And SnowparkSubFeed can create an implicit SnowparkLanguageImplementation before doing the same. A demo of how it works can be seen in [SparkLanguageImplementationTest](https://github.com/smart-data-lake/smart-data-lake/blob/feature/376-dataframe-dsl/sdl-core/src/test/scala/io/smartdatalake/dataframe/SparkLanguageImplementationTest.scala).

We will have some trouble with types though, because Snowpark has different types than Spark. Snowpark has wrappers for the Snowflake types, which behave differently than Spark types in many cases, especially complex types like arrays or structs. Type projections will probably have to be re-thought completely for Snowpark, and it is currently rather tightly coupled to HistorizeAction as far as I can tell.

I am not sure where the best place to make the cut between Spark- und Snowpark-specific code and DSL transformation code should be. Probably in SparkActionImpl and SnowparkActionImpl. This would mean changing around the inheritance hierarchy a bit, because currently e.g. HistorizeAction inherits from SparkOneToOneActionImpl, which sounds Spark-specific but probably need not be.

Maybe we could arrange a call some time and discuss this proposal?

**Comment by MarkusRothSBB** [comment]
CustomSnowparkAction is merged, so I am closing this issue. Further integration if Snowpark/Snowflake can be discussed in further issues.
