### ISSUE TITLE
Implementation of StateListener in own project and extend metrics with read statistics

### ISSUE THREAD

**Issue by buol00** [smart-data-lake/smart-data-lake#454]
**Is your feature request related to a problem? Please describe.**
At the current state it is not possible to implement the StateListener as a scala class in your own project, since the class ActionDAGRunState is defined private related to the smartdatalake package, compare code example.

`package my.package.monitoring

import io.smartdatalake.app.StateListener
import io.smartdatalake.workflow.{ActionDAGRunState, ActionPipelineContext}

class ProjectStateListener extends StateListener {
  override def notifyState(state: ActionDAGRunState, context: ActionPipelineContext): Unit = {
    // no access to state variable (ActionDAGRunState is private[smartdatalake] )
  }
}
`
A workaround is to implement the StateListener in Java.

**Describe the solution you'd like**
Related to the circumstance described one solution is to make ActionDAGRunState class public.
Further we would like to get access to spark read statistics (taskEnd.taskMetrics.inputMetrics.bytesRead and taskEnd.taskMetrics.inputMetrics.recordsRead). Is it possible to extent the metrics in the StateListener with dataObject read statistics?

**Comment by zzeekk** [comment]
Hi @buol00, you are right, it makes sense to make ActionDAGRunState, RuntimeInfo and DataObjectState public.

Metrics are collected generically per Action and output DataObject as a Map[String, Any].
They are accessible through `state.actionsState(<actionId>).results.find(_.subFeed.dataObjectId==dataObjectId).map(_.mainMetrics)`.
For Spark the collection of metrics is done by a SparkStageMetricsListener as SparkStageMetrics. 
SparkStageMetrics implements trait ActionMetrics and implements method getMainInfos, which is used to fill mainMetrics above. It makes the following metrics available for each output DataObject:
`Map("stageDuration" -> stageRuntime, "records_written" -> recordsWritten, "bytes_written" -> bytesWritten, "num_tasks" -> numTasks.toLong, "stage" -> stageName.split(' ').head)`

As i understand you would like to get additional read statistics. The problem here is that it's already not so easy to find the Spark stage relevant to write a DataObject, as there normally are multiple stages (read, joins, groupBy's, write...) and multiple Actions can run in parallel. As SDLB creates one Spark job by Action and output DataObject, it can set the Action and DataObject name in sparkSession.sparkContext.setJobGroup, and assign metrics received back to the action and output DataObject. Then SDL takes the metrics from the latest stage as output metrics.
To get read metrics from SparkStageMetricsListener i dont know how to assign Spark metrics received to input DataObjects in an Action with multiple inputs. If you have an idea let me know.

A alternative solution could be to implement custom metrics which count the number of input records per DataObject, see also open issue https://github.com/smart-data-lake/smart-data-lake/issues/377
