### ISSUE TITLE
Remote agent for optimized on-premise to cloud ingestion

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#481]
**Is your feature request related to a problem? Please describe.**
Ingesting on-premise data sources to a cloud analytics plattform has challenges like
- network / firewall security: if there is no VPN, often only outbound traffic is allowed
- limited bandwidth: VPN bandwith is limited and costly, public internet connection is limited as well

If SDLB could run an Action in a remote environment like an on-premise machine, we could use all SDLB connectors to read data and create and transfer highly compressed Parquet file to cloud storage. If the remote agent is controlled by a long running outbound HTTPS-connection (e.g. Azure Relay), we can solve both challenges.

**Describe the solution you'd like**
First step: implement an Dummy SDLB remote agent controlled through a Java interface. Communication over network connections and Azure Relay can be added later in different remote agent protocol implementations using the same java interface.

An SDLB job can ask a Remote Agent to execute an Action. The request includes the fully parsed configuration (Remote Agent does not need access to the configuration files and parse them) of the Action (can we serialize an Action including DataObjects and Connections?) and the operation to be executed (prepare, preInit, init, preExec, exec, postExec, see also Action). The operation is blocking, e.g. it will only return when finished, and has to return the corresponding result for the operation. If the result is a SubFeed and includes a DataFrame, this will only include the Schema but no data (e.g. the schema must be serialized, but the DataFrame is created empty and the SubFeed must be marked with isDummy=true).

To configure an Action for remote execution, an additional property "execution-agent" can be set. It refers to an agent definition (new top-level configuration element). An agent definition has a type (e.g. Dummy, Azure Relay, ...) and the informations to connect to the agent.

TBD: how do we override the connection configuration used for Actions when executed on a remote agent? I would like to limit the scope of overrides to connections, and it would be nice if this is parsed and validated within every normal config parsing.

**Comment by Geheiner** [comment]
I have these plans for the serialization of actions, dataObjects and connections: I intend to serialize the entire instanceRegistry to a HOCON Config File and send that one as a Text String via the websocket from the Master to the Agent.
We will remember the completely parsed config for each ConfigObject when it is initialized, that way we can also support multiple config files and variable substitutions within the original HOCON Config.

**Comment by zzeekk** [comment]
In the description we have the following open point:
how do we override the connection configuration used for Actions when executed on a remote agent?

I have the following suggestion:
We will have agents as new top-level configuration elements. I suggest that each agent has list of connections. When sending Action/DataObjects/Connections configuration to the agent, connections are replaced by a Connection with the same name potentially defined in the Agents connection list. If there is no connection with the same name for this agent, the original connection is sent to the agent. What do you think?

**Comment by Geheiner** [comment]
> If there is no connection wit

Yes, that sounds good. All DataObjects that use agents should therefore have a connection assotiated with them

**Comment by Geheiner** [comment]
Currently, I'm thinking of the following way of implementing it. 

There exist two instances of SDLB: 
- the "Main instance of SDLB" that orchestrates the whole execution of the DAG
- the "Remote instance of SDLB" that waits to  be triggered by the main instance to execute a RemoteAction

I'm imagining that there exists only one DAG config file and the Main Instance has access to it.
Let's say the Main instance starts executing the DAG specified by the config.
If an action has it's field remoteActionConfig specified (which specifies how to reach the remote Agent, for example with a remoteAgentURL), the Main instance will serialize to a HOCON String the action, it's input and output dataObjects as well as the assotiated connections. Password fields will be filled with a dummy value. This information is sent to the Remote Instance via a websocket.
The Remote Instance will directly execute the Configuration he received and notify the main instance once it's finished.
The main instance blocks until the remote Instance is finished.
The Remote Instance receives all information it needs to run the action from the websocket, except passwords. Passwords shall be given to the Remote Instance as environment variables when it is started. This can be implemented with io.smartdatalake.util.misc.EnvironmentUtil#getSdlParameter, where the Remote Instance will be replacing the contents of the password fields that it received with the contents of the environment variables of the same name.

What's currently a bit unclear to me is what should be done after the Remote Instance is finished executing the Action.

1. Probably, the Main Instance should have "an up to date pointer" of the output dataObjects of the RemoteAction so that the following Actions of the Main Instance can use the results of the RemoteAction and everything can be executed in one DAG. Should this be done automatically as soon as the RemoteAction is done? Or should this be configurable?

2. Probably, the RemoteInstance needs to send the schema of the output dataObject to the Main Instance so that it can work with it until the INIT Phase

**Comment by zzeekk** [comment]
Hi @Geheiner, thanks for the updated ideas. Some thoughts from my side.

1) I propose to introduce new top level objects RemoteAgent (or just Agent?) which hold the configuration how to reach the remote agent. An action can then be configured to run remotely by setting the id of the RemoteAgend in the remote-agent property. A RemoteAgent has a list of connections, which are used to lookup up the connection configured in the DataObject instead of the connection in the top level Connection list. WDYT?

2) Regarding Passwords - if we send the configuration as Json as proposed by #575, secret providers are not yet resolved, therefore no passwords in the configuration as described by you. On the otherside i also think that it could be interesting to have the secret providers resolved on the MainInstance. If we are working on remote places (e.g. on-premise VM) we often have no proper key vault and use environment variables as described by you. It would be nice to use the Azure Key Vault on the main instance, and send the password to the RemoteAgent. WDYT?

3) Regarding the result that the RemoteAgent should return to the MainInstance - in my opinion it should work like a remote execution of the init or exec function, this means the RemoteAgent should serialize the resulting Seq[SubFeed] and sent it back to the MasterInstance over websocket. The MasterInstance waits in an init/exec function for the result, will deserialize it and returns it. We can implement this like an additional ser/de layer, e.g. we have a RemoteStubAction on the MasterInstance coordinating the remote execution, like in the good old Java RMI framework. WDYT?

**Comment by Geheiner** [comment]
OK, so if I understand point 1. correctly, we have only one central HOCON configuration to which the main instance has access.  
This config contains a new section called agents, which has a defined list of Agents.
An Agent definition contains information on how the main instance can reach it, as well as it's own list of connections.
When the main instance sends instructions to the agent, connections defined in the 
top-level list of connections get overwritten by connections defined in the Agent's connections when they have the same id

**Comment by pgruetter** [comment]
@Geheiner : Do you have an overview of this issue? Was everything done with #582 ? If not, can we split this issue in the done part and in open part for one of the next milestones?

**Comment by Geheiner** [comment]
Hi @pgruetter 
Yes, everything described in this issue was done.
What's left is just to update the documentation (work in slow progress on my side).
Next step is to actually use the feature in a realistic scenario, it has only been tested with dummy pipelines so far
