### ISSUE TITLE
CopyAction with parameter deleteDataAfterRead = true deletes not only data, but also the containing directory

### ISSUE THREAD

**Issue by burriad** [smart-data-lake/smart-data-lake#484]
**Describe the bug**
Since version 1.3.2, the CopyAction not only deletes the data when flag deleteDataAfterRead is set, but also the directory. This causes the next run to fail, since it tries to write files into an inexistent directory 

**To Reproduce**
-

**Expected behavior**
When deleteDataAfterRead is set, only the data shall be deleted

**Additional context**
-

**Comment by burriad** [comment]
Tried to provide evidence that version 1.3.1 hasn't that problem, but the behaviour is indeed the same

**Comment by zzeekk** [comment]
Hi @burriad, 

Actionally CopyAction deletes partition folders when processing partition wise (including partition directory, because an empty partition directory means the partition exists but has no data...), and all files otherwise.
Implementation see: https://github.com/smart-data-lake/smart-data-lake/blob/040e85ee1f325a8e243cb0f5deeabd0fd079b8c8/sdl-core/src/main/scala/io/smartdatalake/workflow/action/CopyAction.scala#L106

For FileTransferAction there is also an executionMode=FileIncrementalMoveMode, which deletes all files processed.
