### ISSUE TITLE
Secrets as general variable

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/smart-data-lake#571]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to provide secrets also for other parameters, beside of *BasicAuthMode*, e.g. for spark options to specify storage keys.

**Describe the solution you'd like**
As a user, I want to be able to specify in the global section my variables I then can use anywhere in the hocon configuration as local variable. Here an example where we want to use storage name and key in the spark options, but the variables could also be used in other sections:

```
global {
  secrets {
     myArbitraryVariable = "<SecretProviderId>#<SecretName>"
     myStorageName = "AZKV#StorageName"
     myStorageKey = "AZKV#StorageKey"
  }
  spark-options {
    "spark.hadoop.fs.azure.account.key."${global.secrets.myStorageName}".dfs.core.windows.net" = ${global.secrets.myStorageKey}
  }
}
```

**Comment by zzeekk** [comment]
This could be more difficult to implement as we initially thought, as the Hocon substitutions will be resolved when parsing the configuration. But resolving secrets is done when they are used, e.g. the prepare phase.
Maybe we could use some "Java dynamic proxy" approach to resolve secrets on the fly when used. The dynamic proxy would be setup when parsing the configuration?
see also https://www.baeldung.com/java-dynamic-proxies

**Comment by zzeekk** [comment]
I check various approachs to fake (e.g. extend) Java String class with @ddeuber, without success (javaassist, ByteBuddy, Dynamic Proxies). Java is really strict in not allowing to extend final classes and primitive types.

I would propose a less generic approach, but still nice and (mostly) backward compatible - Lets introduce a StringOrSecret class and implement an implicit ConfigReader for it (see existing readers in io.smartdatalake.config.ConfigImplicits). By using a convention the resolution using secret provider is triggered, e.g. `"###<provider>#<secretname>###"`. If the convention is met, value() returns the secret, otherwise it returns the original String value of the configuration. The type of all parameters where we would like to use secrets needs to be changed from String to StringOrSecret. This is backward compatible for the configuration.
But i think we should also cleanup existing parameters named userVariable or pwdVariable, which are parsed using SecretProvider. We should rename them to user and pwd, maybe supporting both for some time and marking them as deprecated?

**Comment by mand35** [comment]
This sounds great for me. 
The other question is how the user realize where he/she can use a secret without looking into the code. Do we always need to mention in the `@params` comment or can we solve more automated?

**Comment by ddeuber** [comment]
In the JSON schema, the Scaladoc of `StringOrSecret.parameter` is automatically added to the description of all secrets. So the user can see in the schema viewer whether a secret can be used.

![image](https://user-images.githubusercontent.com/10706639/225860072-795b804d-30ae-46fd-b898-7a509c8671fd.png)
