### ISSUE TITLE
Possibility to write case sensitive column name through JDBC

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#619]
**Is your feature request related to a problem? Please describe.**
Currently when you write data to a JdbcTableDataObject, columns are converted to lowercase:
https://github.com/smart-data-lake/smart-data-lake/blob/10d8c9e2cb5f7ad35d6be2a25df015923389e689/sdl-core/src/main/scala/io/smartdatalake/workflow/dataobject/JdbcTableDataObject.scala#L195
This is not always desirable, i.e. when doing 1:1 data migrations and you want to keep the source names. 

**Describe the solution you'd like**
I propose to use the setting of `spark.sql.caseSensitive` that we can already get through `SchemaUtil` to decide whether to use case sensitive column names or not:
`if (SchemaUtil.isSparkCaseSensitive) df else df.colNamesLowercase`

**Additional context**
- Maybe implicitly using the spark setting is not the best option and we should make it configurable for each data object / every connection
- Another problem is using column names with Dots.

**Comment by zzeekk** [comment]
Good point that was also on my list. I propose to use StandardizeColNamesTransformer transformer in actions reading from such DataObjects, and remove colNamesLowercase in JdbcTableDataObject.getSparkDataFrame completely. StandardizeColNamesTransformer has options to customize the behaviour:
- camelCaseToLower replaces uppercase letters with underscore and lowercase letter
- normalizeToAscii converts UTF-8 special characters (e.g. diacritics, umlauts) to ASCII chars
- removeNonStandardSQLNameChars removes all chars from a string which dont belong to lowercase SQL standard naming characters, i.e abc$!-& -> abc
By default they are all enabled.

Drawback is that this is not backward compatible in 2 points:
- it doesnt support yet the simple colNamesLowercase as implemented today, because it inserts underscores...
- it needs an additional transformer in the configuration

@pgruetter: do you think this could be a way forward if we add a legacy colNamesLowercase  to StandardizeColNamesTransformer? Or even a different Transformer that implements the colNamesLowercase mode? Probably as breaking change in 2.5.0 version?

**Comment by pgruetter** [comment]
Yes, I think a breaking change is OK in this case. We need to have a deeper discussion about this. 
But the default should probably be: don't do anything to the column names (at least for JDBC Data Objects). This includes special characters that need to get supported.
Then, it still needs to be possible to manipulate the naming as generically as possible (i.e. CamelCase to lowercase conversion for all actions).

**Comment by ddeuber** [comment]
I found some additional points which need to be addressed:

* `SchemaUtil.isSparkCaseSensitive` is not always resolved correctly, i.e. although `spark.sql.caseSensitive=true`, it resolved to `false`.  For example at:

https://github.com/smart-data-lake/smart-data-lake/blob/f5d7d2c31ee1d05a2bc1e7dc567f8ef7f17a9cd8/sdl-core/src/main/scala/io/smartdatalake/workflow/connection/JdbcTableConnection.scala#L176

* The lower casing of column names also needs to be disabled for other data objects, otherwise you might loose the capitalization during a staging layer. For example, `ParquetFileDataObject` also uses `colNamesToLowerCase`.

**Comment by ddeuber** [comment]
The problem with `SchemaUtil.isSparkCaseSensitive` is that `SQLConf` does not resolve the current config value correctly:

https://github.com/smart-data-lake/smart-data-lake/blob/655dd060911cf23b08c5fbf43461d7e6faa7feb5/sdl-core/src/main/scala/io/smartdatalake/util/misc/SchemaUtil.scala#L120-L122

`SQLConf` is an internal Spark class and `SQLConf.get` does not seem to be able to resolve the correct SparkSession to take the config from. Instead we could use `sparkSession.conf.get("spark.sql.caseSensitive")`, but the problem is we need a Spark session as a parameter, which is not always available because  `SchemaUtil.isSparkCaseSensitive` is often used in schema operations etc.

One approach to fix this is to create an SDL config parameter `GlobalConfig.caseSensitive` and we use it instead. To make sure we are consistent with Spark we would set `spark.sql.caseSensitive`  according to `GlobalConfig.caseSensitive`. If the configuration contains an inconsistent value of  `spark.sql.caseSensitive` we could throw an error. 

Or we just check if `GlobalConfig.sparkOptions`  contains ``spark.sql.caseSensitive = true`.

What do you think @zzeekk @pgruetter ?

**Comment by pgruetter** [comment]
Having a new (optional) global option sounds good to me. But if we do set a new parameter, I think we should give the possibility to overwrite it on a connection level.
Maybe you read from a JDBC source and need to have case sensitivity, but once you loaded your data, you want to continue with the default behavior. In that case you would't set it on the global level, only on the JDBC connection.

**Comment by ddeuber** [comment]
Then we would also need to set `spark.sql.caseSensitive` when interacting with this connection. We use a global SparkSession in SDL, right? So changing `spark.sql.caseSensitive` at one point might interfere with operations for another connection, e.g. if `parallelism > 1`.

**Comment by ddeuber** [comment]
I tried getting `spark.sql.caseSensitive` from `Environment.sparkSession.conf`, which leads to NPEs because the Spark session is not yet initialized when it is used. This may also be the reason why `SQLConf` does not always return the correct configuration, because it returns the default configuration if no Spark session is found.

**Comment by ddeuber** [comment]
We decided to introduce a new environment property `Environment.caseSensitive` which used to determine if case sensitivity should be enabled.
