### ISSUE TITLE
Issues with JdbcTableDataObject in 2.4.1

### ISSUE THREAD

**Issue by ddeuber** [smart-data-lake/smart-data-lake#633]
There are multiple issues when using JdbcTableDataObject in version 2.4.1:

1. For dropping tables like temporary tables, the query `drop table if exists $tableName` is used. This query is not valid for Oracle databases.
2. When creating to temporary tables, the schema of the dataframe is used to determine the schema of the temporary table. When saveMode=Overwrite, this leads to problems when the order of the columns is not the same in the dataframe as in the database table, because the order of the columns of the temporary table needs to match the order of the target table, otherwise the insertion with `insert into $table from $temporaryTable` will fail. 
3. Many JDBC drivers use auto-commit per default. When calling `commit` in SDLB, the Oracle JDBC driver throws an exception `java.sql.SQLException: Could not commit with auto-commit set on`. The error can be disabled by providing the JVM option `-Doracle.jdbc.autoCommitSpecCompliant=false`. However, I am not sure whether it makes sense to have auto-commit enabled if SDLB manages the transactions manually.

**Comment by zzeekk** [comment]
Hi @ddeuber, for 3) the reason is as follows: on saveMode=Overwrite we delete data in a separate statement and insert new data in a second statement. With auto commit enabled these are separate transactions and the data is missing for a short period of time. I recommend to disable auto commit to have transactional overwrites. But we could integrate the following configuration options:
1) Attribute enableCommit: Boolean = true, which can be disabled to use auto commit mode.
2) Attribute connectionInitSql: Option[String] = None, which is run whenever this DataObject creates a JDBC connection. It can be used to disable auto commit for this DataObject by SQL configuration.
May be could put both configuration attributes on JdbcTableConnection.
WDYT?

**Comment by ddeuber** [comment]
I like the idea, it gives the user more flexibility without changing the current behaviour. For a future major version we can evaluate whether we want to disable the auto-commit mode per default, I will create a separate issue for this task.

**Comment by ddeuber** [comment]
When testing I found that Oracle does not allow to set the auto-commit mode via a query. For Oracle, auto-commit behaviour is provided by the client / driver. Therefore, I propose we add a property `autoCommit: Option[Boolean] = None` which uses the default behaviour of the JDBC driver if it is not set and otherwise sets the auto-commit mode. Nevertheless, I would keep `connectionInitSql`, it is definitely useful if you want to set some session parameter. Is that ok for you @zzeekk ?

**Comment by zzeekk** [comment]
@ddeuber: You mean "SET AUTOCOMMIT OFF;" wont work via connection.execJdbcStatement(preparedSql)?

**Comment by ddeuber** [comment]
Yes, i get
`Caused by: Error : 922, Position : 4, Sql = set autocommit off;, OriginalSql = set autocommit off;, Error Msg = ORA-00922: missing or invalid option`

**Comment by zzeekk** [comment]
And what about `alter session set autocommit = false;`?

**Comment by ddeuber** [comment]
Same problem:
`Caused by: Error : 2248, Position : 18, Sql = alter session set autocommit = false;, OriginalSql = alter session set autocommit = false;, Error Msg = ORA-02248: invalid option for ALTER SESSION`

**Comment by zzeekk** [comment]
Yes, lets create an `autoCommit: Option[Boolean] = None` configuration attribute :-)
And i also agree to keep connectionInitSql, could be usefull nevertheless.

**Comment by ddeuber** [comment]
Resolved with version 2.4.2
