### ISSUE TITLE
SchemaViewer is freezing when loading definitions

### ISSUE THREAD

**Issue by dnLeiting** [smart-data-lake/smart-data-lake#644]
The SchemaViewer on the SDLB web page shows the hierarchical structure of schemas existing in the SDLB. Navigating through the schema tree works fine by clicking the circle of a specific component. But when clicking on different schemas to load the definition, the SchemaViewer gets stuck for multiple seconds.

To reproduce the bug, please visit the SDLB webside: http://smartdatalake.ch/JsonSchemaViewer
To load the definition and reproduce the described behaviour, click on the name of a schema.

The bug free behaviour would be, that the definitions load directly without freezing the website.

**Comment by ddeuber** [comment]
We found that this only affects Firefox but not Chrome or Edge.

**Comment by ddeuber** [comment]
Firefox spends a lot of time on redrawing when `setInfo` is called due to a click. See Reflow in the profiling report:

![image](https://user-images.githubusercontent.com/10706639/233649039-e3fc9533-cffd-4718-8043-c0cf9f21be6a.png)

This might be a jQuery problem. I think we should discuss if it is worth fixing this with jQuery, because if we plan to modernize the schema viewer with React then this issue might very well be fixed.
