### ISSUE TITLE
Improve build speed

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#647]
**Is your feature request related to a problem? Please describe.**
Builds are taking already up to 45mins. This is quite a long time.
Ca 10mins are compiling, 35mins are unit tests. Tests could be optimized for sure.
But it could be speed up by using maven parallel builds (https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3), which would build modules in parallel, but not sure how many cores we have on Azure DevOps. I'm also not sure if unit tests from different modules would run in the same JVM. There might be concurrency issues with global objects such us Environment.
There might be other concurrency issues because of same DataObject paths used in different modules...

**Describe the solution you'd like**
Analyse and make build process faster...

**Comment by ddeuber** [comment]
The problem with parallel tests is that they introduce nondeterministic behaviour. If the tests are not totally isolated from each other, there will be test failures which are very hard to debug. Then, people usually start to just run the build multiple times until it passes. This results in a lot of frustration because one is never sure whether the build has failed due to a change or because it is flaky.

**Comment by zzeekk** [comment]
Improvment implemented:
Unit tests were executed twice in snapshot_builds.yml, once for goal 'test' and once for scoverage:report.
By using goal 'compile' instead of 'test', unit test get executed only once by scoverage:report.
