### ISSUE TITLE
Test SaveMode = Overwrite

### ISSUE THREAD

**Issue by iliassoto** [smart-data-lake/smart-data-lake#654]
The following combination of data objects and one action must be thoroughly tested and it's functionality asserted. The combination is the following:
- **Input Data object**: {
type = ParquetFileDataObject
saveMode = Overwrite
}

- **Output Data object**: {
type = DeltaLakeTableTableDAtaObject
saveMode = Overwrite
}

- **Action**: {
type = CopyAction
executionMode.type = FileIncrementalMoveMode
<OPTIONAL> transformers = [AdditionalColumnsTransformer] <OPTIONAL>
}

The reason for this issue is that some tests showed unexpected behaviour using these options.

**Comment by moskast** [comment]
I tried all possible combinations of input-data (i), output-data(o) and action (a) with either Overwrite (o) or Merge (m).
I think that the last mode overwrites the one before.
Because the saveMode was always the same as the action's. I also tried it with just input and output-data (a0) and then the saveMode mirrored the one from the output-data.

My results were the following:
1. ioooao: overwrite
2. imooao: overwrite
3. ioomao: overwrite
4. ioooam: merge
5. imomao: overwrite
6. imooam: merge
7. ioomam: merge
8. imomam: merge
9. iooma0: merge
10. imooa0: overwrite

My config for this test: [application.conf](https://github.com/smart-data-lake/smart-data-lake/files/12882330/application.conf.txt)
I tried it both with executionMode.type = FileIncrementalMoveMode and without, it did not affect the results.

**Comment by iliassoto** [comment]
Thank you @stemike ! 

Then the tests worked as they should (see class DataFrameActionImpl)

https://github.com/smart-data-lake/smart-data-lake/blob/866810241d4bdd4c93f5e9a949dee877aacb52a9/sdl-core/src/main/scala/io/smartdatalake/workflow/action/DataFrameActionImpl.scala#L78-L82

Thank you for testing! @patrickgruetter I guess we can close this issue?

**Comment by pgruetter** [comment]
@stemike Thanks for the extensive tests! Do you see any unit tests we should extend?

**Comment by moskast** [comment]
I don't think there are any tests concerning this issue.
