### ISSUE TITLE
Symbol `inner` does no more exist since SDL 2.5.0

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#717]
Well, it's more a question than a bug. 

With 2.4.2 this method worked well and returned a `DataFrame`:
```scala
  private def validate(fileType: String, dfPrep: DataFrame): DataFrame = {
    val inputSubFeeds = Seq(
      SparkSubFeed(Some(SparkDataFrame(dfPrep)), DataObjectId(s"${fileType}_prep"), Seq()),
    )
    val config = SmartDataLakeBuilderConfig(feedSel = s"ids:mvr-validate-$fileType", applicationName = Some("test"), configuration = Some(Seq("test")))
    val sdlb = new DefaultSmartDataLakeBuilder()
    val (finalSubFeeds, _) = sdlb.startSimulation(config, inputSubFeeds)
    finalSubFeeds.find(_.dataObjectId.id == s"${fileType}_validated").get.dataFrame.get.inner.cache()
  }
```

Now with 2.5.0 the symbol `inner` does no more exist. What can I do to get this working again? Maybe @ddeuber has an idea?

Thanks very much in advance.

Kind regards,
Adi

**Comment by AdiWehrli** [comment]
Remark: wouldn't it be a nice idea, to set methods/classes to `@deprecated` (with a description, what would be next to do) prior to deleting them directly? 😉

**Comment by zzeekk** [comment]
Hi @AdiWehrli, actionally the SparkDataFrame still has an `inner` attribute, but i think the return value of startSimulation changed to be more generic (commit of Februar 23). It returns Seq[DataFrameSubFeed] instead of Seq[SparkSubFeed] before.

In your test you would need to cast the dataFrame to a SparkDataFrame as follows:
`finalSubFeeds.find(_.dataObjectId.id == s"${fileType}_validated").get.dataFrame.get.asInstanceOf[SparkDataFrame].inner.cache()`

On the other side cache() is also implemented on the GenericDataFrame, means you could just write
`finalSubFeeds.find(_.dataObjectId.id == s"${fileType}_validated").get.dataFrame.get.cache()`

I agree with you comments on marking deprecated stuff. We do this already for configuration objects/attributes, which is our main API. We also decided to make more Scala objects public in order to have more flexibility for customizations in projects. But we probably cant keep this more "developer" oriented API always backward compatible between minor releases. In the case above this would have been difficult anyways, because it was not a removal, but just a more generic return type...

**Comment by AdiWehrli** [comment]
Thanks very much, @zzeekk. I'll try this. 😊

**Comment by AdiWehrli** [comment]
It worked. Thanks very much.
