### ISSUE TITLE
Error while writing to Postgres

### ISSUE THREAD

**Issue by eliasarnold** [smart-data-lake/smart-data-lake#748]
**Description**
There seems to be a bug regarding the authentication of SDLB on PostgreSQL DB. The error message says that the '_sdltmp' table could not be created.

**Reproduction**
The error occurs when an attempt to write in a Postgres DB is made. The following three configuration objects are needed to reproduce the error:
```
conn_postgres_db {
    type = JdbcTableConnection
    driver = org.postgresql.Driver
    url = "jdbc:postgresql://localhost:5455/postgres"
    db = keytool_dbo
    authMode {
      type = BasicAuthMode
      userVariable = "<yourUser>"
      passwordVariable = "<yourPW>"
    }
  }
```

```
tgt_About {
    type = JdbcTableDataObject
    connectionId = conn_postgres_db
    table {
      name = about
    }
  }
```

```
migrate_About {
    type = CopyAction
    inputId = ext_About
    outputId = tgt_About
    transformers = [{
      type = StandardizeColNamesTransformer
      camelCaseToLower = false
    }]
    metadata {
      feed = migrate
    }
  }
```

**Expected behavior**
SDLB should be allowed to create new tables in Postgres.

**Additional context**
In my case, the referenced `ext_About` object is a table named "About" in a MS SQL Server DB. The configuration looks like this:
```
conn_mssql_db {
    type = JdbcTableConnection
    url = "jdbc:sqlserver://localhost:1433;database=keytool;encrypt=false;trustServerCertificate=true"
    driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
    db = dbo
    authMode {
      type = BasicAuthMode
      userVariable = "<yourUser>"
      passwordVariable = "<yourPW>"
    }
  }
```
```
ext_About {
    type = JdbcTableDataObject
    connectionId = conn_mssql_db
    table {
      name = About
    }
  }
```
However, I think the fact that the source is MS SQL Server is not specific for the error.

**Comment by zzeekk** [comment]
The issue is caused by Postgres "transactional DDL" feature, means that DDL statements like "create table" are also executed in a transaction. This is different from most other DBMS systems. See also https://franckpachot.medium.com/transaction-management-in-postgresql-and-what-is-different-from-oracle-eeae34675a77
The example above works if setting JdbcTableConnection "autoCommit = true".
I dont understand yet why it doesnt work with autoCommit = false, because SDLB is executing conn.commit() after the statement. But somehow it seems that a transaction is not properly initiated for Postgres like that...

**Comment by zzeekk** [comment]
Found the problem - Postgres handles transactions more consistent. Before the failing create statement a "select 1 from <tableX>" is executed to check if a table exists. As the table doesn't exist there is an exception and as this runs in a transaction, Postgres fails the transaction. Then, in Postgres, you have to rollback the transaction, before you can run another statement. See PR for the fix.
